### ISSUE TITLE
Test output is not properly escaped which breaks XML

### ISSUE THREAD

**Issue by ghost** [freckle/hspec-junit-formatter#27]
We are facing some weird error in [our CI](https://github.com/input-output-hk/hydra/issues/1126) which is indirectly caused by hspec-junit-formatter: We have tests that output the result of rendering with [brick](https://hackage.haskell.org/package/brick) which contains formatting characters which are not properly escaped or erased, which breaks a GH plugin we are using to report test results that parses XML file.

It seems to me a relatively simple solution would be to wrap the text output into a `<![CDATA[ ... ]]>` section which is guaranteed to not be interpreted by the XML parser.

**Comment by pbrisbin** [comment]
It seems like we might already have a fix on `main`, that just hasn't been released yet. https://github.com/freckle/hspec-junit-formatter/commit/5217b8f52e09f1aa99c1c4abe70526bc12dafd73

That fix drops formatting characters rather than using `CDATA`. I wonder if `CDATA` would be simpler or offer other benefits worth doing instead, WDYT @akshaymankar ?

@abailly-iohk would it be possible for you to try our current `main` and see if that fixes your issue? Either way, I will work to cut a new release today / this week.

**Comment by ghost** [comment]
Awesome! Actually, this is what I am doing as a quick fix, sanitizing the output we put in the XML.

**Comment by ghost** [comment]
I am wondering: It seems to me your filtering does not remove _all_ escape characters, only the ones about colors. Am I wrong?

**Comment by pbrisbin** [comment]
I think that was the intent, but I have to defer to @akshaymankar as the one who implemented it.

**Comment by akshaymankar** [comment]
Yes, I was focusing on colours because that was my problem. I found the regex somewhere and it made sense so I used. It is possible that bricks prints out more ANSI escape codes than just colours. 
Later I also found this function in hspec which does this without the regex dependency: https://github.com/hspec/hspec/blob/9b6bdf3ab38252c560628b9e437bb1d2ee8a815e/hspec-core/src/Test/Hspec/Core/Util.hs#L75-L85
Perhaps this is more comprehensive.

**Comment by pbrisbin** [comment]
Wrapping things in `CDATA`, and doing no stripping, seems simpler, less brittle, and strictly more useful (albeit far-fetched that you might want to preserve formatting in the XML report, it is conceivable someone would use it in an environment that can render them). Is there any downside to that approach?

Otherwise, I agree that `stripANSI` by hspec seems better than hand-rolling our own regex thing.

**Comment by abailly** [comment]
I have not dealt with XML for the past 10 years or so, but according to my book, you can put anything which conforms to the expected file encoding in a CDATA section and it's not parsed.

**Comment by pbrisbin** [comment]
:wave: is there any work left open on this Issue? Please correct me if I'm wrong...

1. We are stripping color escapes, so the original issue is fixed
2. We could move to `Test.Hspec.Core.Util.stripANSI`

   This would be good since it's upstream-maintained, and strips all ANSI, not just colors.

3. We could remove any stripping and instead use `CDATA`

   This would be good because it actually preserves everything, without breaking XML.

But no one is actively working on (2) or (3).

I'm going to optimistically close this Issue, but please re-open (or open something new) if necessary.

**Comment by abailly** [comment]
@pbrisbin Thanks a lot for addressing the initial issue, that's a good tactical solution 👍 And my apologies for not having replied earlier
